{% include "addAssertion.js" %}
{% include "badgeExists.js" %}
{% include "checkPassword.js" %}
{% include "doHash.js" %}
{% include "emailRecipient.js" %}
{% include "generateUid.js" %}
{% include "getBadgeNames.js" %}
{% include "handleRequests.js" %}
{% include "readFile.js" %}
{% include "submitForm.js" %}
{% include "validateInput.js" %}
{% include "validateValue.js" %}
