{% include "addAssertion.js" %}
{% include "buildAssertionJson.js" %}
{% include "buildBadgeJson.js" %}
{% include "checkPassword.js" %}
{% include "createContentService.js" %}
{% include "doHash.js" %}
{% include "emailRecipient.js" %}
{% include "generateUid.js" %}
{% include "getBadgeNames.js" %}
{% include "handleRequests.js" %}
{% include "readFile.js" %}
{% include "submitForm.js" %}
{% include "validateInput.js" %}
{% include "validateValue.js" %}
